### ISSUE TITLE
TR3 - RX Minecart Enemy Check on Cavern Slot

### ISSUE THREAD

**Issue by DanzaG** [LostArtefacts/TR-Rando#269]
If RX is on cavern slot, Flamethrower lads will be agressive. This is an issue when getting off the first minecart as theres a flamethrower by default right next to it. Also with enemy rando, a worst case of 2 angry flame lads right next to the minecart is possible.

Idea would be to restrict enemy spawns in radius of a minecart to not be a flamethrower if level slot is cavern.

**Comment by lahm86** [comment]
Resolved under #270.
