### ISSUE TITLE
Runtime Error when using CTRL+S

### ISSUE THREAD

**Issue by SlyRaider** [LostArtefacts/TR-Rando#346]
Hello,

While playing, I sometimes use the CTRL+S key combination by mistake several times in a game, and the game crashes with the following Windows error message:

![runtime-error](https://user-images.githubusercontent.com/14979983/182050077-42452dcc-8148-40aa-8705-044a1cdd69f0.jpg)

Is that possible to fix that, please?

**Comment by lahm86** [comment]
This would need to be resolved in the executable itself, so it may be worth raising an issue for TR2Main.
