### ISSUE TITLE
TR1 Rando

### ISSUE THREAD

**Issue by REF-2021** [LostArtefacts/TR-Rando#394]
Hi! Probably being really stupid here, but when I try to randomise TR1 (ATI), and error occurs in that 'MainMenuPicture' is missing. Thanks for your help!

**Comment by lahm86** [comment]
> Hi! Probably being really stupid here, but when I try to randomise TR1 (ATI), and error occurs in that 'MainMenuPicture' is missing. Thanks for your help!

Try a clean install, it sounds like there are maybe remnants of an old Tomb1Main install in the game folder. Choose File > Empty Recent Folder List in the randomizer, and then carry out a full reinstall of the game. If you want to use Tomb1Main (recommended for best experience) you can follow the video below to get everything setup.

https://youtu.be/WfyHin4Hpgs
