### ISSUE TITLE
TR1 Remastered.

### ISSUE THREAD

**Issue by luiswebber** [LostArtefacts/TR-Rando#612]
Hello everything is fine?

I know Random wasn't made for TR1 Remastered, but it would just be a question.

When I copy the files generated with Random only with duplicate enemies (clones, using only original enemies from the level) and the option of more items added in the areas to the DATA folder of the TR1 Remastered installation on Steam, they work, except in 3 phases, when I enter the classic graphics these 3 phases work too, but when I switch to the remastered graphics, the game crashes in these 3 areas.

The areas are: St. Francis' Folly - Atlantis and the other one, I don't remember the name of the level, but it's the phase in the file: LEVEL7B.PHD

The funny thing is that it crashes in only 3 areas, it must be due to some incompatibility, but in the rest of the game it works normally with both graphics, the classic or the remastered.

Will a compatible version of the tool for TR1 Remastered ever come out?

It would just be a question.

Thank you very much for the tool, it is a lot of fun.

Hugs.

**Comment by luiswebber** [comment]
Just another addition.

I've already tested without adding new items, in this case I've already tested with only enemies with original clones x3 and the crash continues in the same way.

As I said, I know that the tool was not made for use in TR1 Remastered, but I wanted to leave here the results of my tests, since I can play 12 of the 15 levels of the game in the Remastered version with more items and more enemies with the clones.

I believe that someday a version of the tool will come out that is more compatible with the Remastered version, if that happens it would be really cool.

Thanks!!!

**Comment by lahm86** [comment]
Thanks for the feedback. Yes, currently no testing has been done against the remasters with the randomizer in its current state so you can expect this kind of issue and probably lots more if you randomize more elements. Hopefully there will be support added in the future but there is currently no timeline or roadmap for that.

**Comment by luiswebber** [comment]
Thank you very much for returning my question.

Yes, I noticed that if you make enemies from other phases spawn, for example, appear in other areas, the game also crashes in all areas.

But thank you very much for everything.

Hugs!!!

**Comment by lahm86** [comment]
Closing for now - see #614 for progress.
